### ISSUE TITLE
Diagnostics UI refinements

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1091]
Might need to separate between things to do in first version and what to leave for future improvements.

### Simplified version:
- [x] DiagnosticList page subscription does not provide the last recorded list, so it is always empty on first load (fixed in #1105)
- [x] #1114
- [x] The horizontal line isn't styled with the severity color (fixed in #1115)
- [x] Filter by severity and show chips in a "top bar" (implemented in #1115)
- [x] #1116
- [x] Show some message in DiagnosticListPage if there are no diagnostics to show
- [x] Count badge of number of identified diagnostics on the Left Menu Diagnostics item 
- [x] Left menu icon for diagnostics
- [x] Text wrapping in the list isn't working. (fixed in #1949)
- [ ] Add icons to the severity filter chips
- [ ] Replace severity filter buttons with Chip buttons instead of rounded buttons
- [x] Diagnostic items should not be bold, should be BodyMDNormal, NeutralModerate (fixed in #1949)
- [x] Link color on Diagnostic details page is wrong (should be neutral strong, underline, on hover go to subdued). (fixed in #1960 )
- [x] Diagnostic entry in diagnostic list page should have more padding (fixed in #1949)

**Comment by erri120** [comment]
Closing this as being stale.
