### ISSUE TITLE
App Home Page Add/Remove

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1106]
Users will need the ability to add the game to be managed by the app but also to remove the game from being managed. 

The current tile would be great for this but the button would need to change depending if the game is currently being managed or not. 

In the future we will need to discuss if we need to remove any mods when this happens and if it needs a prompt.  For test candidate focus on add and remove. 

## Designs

- [x] #1069 

[Figma link](https://www.figma.com/file/droQp7IUqRCq5AUGmXldvP/%F0%9F%93%B1-Add%2Fmanage-games?type=design&node-id=1072%3A2728&mode=design&t=1vYPsjdLresFPQtR-1)

[Prototype](https://www.figma.com/proto/droQp7IUqRCq5AUGmXldvP/%F0%9F%93%B1-Add%2Fmanage-games?page-id=201%3A43163&type=design&node-id=1086-4338&viewport=2490%2C-2213%2C0.47&t=BQtyXD2INPsxCGxD-1&scaling=min-zoom&starting-point-node-id=1086%3A4338&show-proto-sidebar=1&mode=design)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/07aad74a-605e-4fc2-869e-c7a7e86c4a5e)

## Breakdown
- [x] #1138
- [ ] Removing Game functionality:
    - [ ] Implement support for deleting Loadouts #399
        - [ ] Remove all FileStore data related to that game?
    - [ ] Implement Dialog box to delete all loadouts for this game
    - [ ] Show Removing Game spinner during removal
