### ISSUE TITLE
Epic: Garbage Collection

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#1174]
# Epic

## Outline
Deleting loadouts and umanaging games, and deleting mods leaves trash in the system, we need a way to "compact" or "cleanup" unused files in the app

## Issues

- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1161
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1186
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1200
