### ISSUE TITLE
Epic: Settings

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1182]
For work related to the settings page.
Discussion to be had around what the settings page will do and what options are needed.

- [x] #396
- [x] #1189
- [x] #1190
- [x] #920
- [x] #1243
- [x] #1370
- [x] #1571
- [ ] #1373
- [x] #1371
- [ ] Add Dialog on save press in there are changes that need user to restart (#1372)
- [ ] Highlight modified settings in the UI (settings that no longer have the default value)
- [ ] Add button to reset to default value in case of modified
- [ ] Add Dialog for Cancel button (You have unsaved changes)
- [ ] Filter search
- [ ] Add developer docs on how to add new settings, before DI settings, and new setting UIs
- [ ] #2303
- [x] #1422
