### ISSUE TITLE
Mod Library Refinements

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1284]
Todo items not implemented as part of initial PR: #1268 
- Mostly blocked on #1276 

### TODO:
- [x] Make list update in real-time (get observable stream from database) (better wait for #1276 )
- [x] Show "-" if we don't have Last installed date or Archive date
- [ ] Downloaded date/time data (put "Manually added" for mod archives not downloaded through the app) #1347
- [ ] Use the Nexus mod name for archives that come from nexus instead of the file name. #1347
- [ ] Version data if available (will not be for archives that don't come from nexus, but for manual archives that come from nexus   it should be possible to obtain the data with an API call, or by parsing the archive name for the embedded version number) #1347
- [ ] Added column data (not sure how to implement this yet, loadouts and mods probably need to be moved to Mnemonic first) #1347
- [ ] Filter out archives that are not manually added or downloaded (don't show nested archives like Installer.dat from SMAPI) #1347
- [ ] Filter entries by game for the current loadout #1347
