### ISSUE TITLE
Reified deletions show up as normal files in Mod Contents View

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1323]
#1302 added implemented reified deletes, so now mods can contain files that represent a deletion.

These files are currently shown as normal files in the Mod Contents viewer (file tree).

How should we handle them?

- [ ] Skip them (we get mods that appear to be empty)
- [ ] Have special icon/styling for those entries
- [ ] Show deletions in a separate tree
