### ISSUE TITLE
MnemonicDB DataModel improvements

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1554]
# Improvement

## Currently 
The way our DB backed data is modelled has some drawbacks and areas that can be greatly improved.

## We want
- [x] Separate read and write interfaces (read only model currently has public setters which makes it confusing)
- [x] #1508 
- [x] Better expression of inheritance relationship between entities
- [x] Clearer understanding of which attributes can be found on a specific entity type
- [x] Better definition of concept of an entity type.
- [x] Better facilities to listen for changes
- [x] Optional Reactive models (notifyPropertyChanged etc)

**Comment by halgari** [comment]
Done as part of #1626
