### ISSUE TITLE
Change references from "Nexus Mods App" to "Nexus Mods app"

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1701]
# Improvement

## Currently 
We refer to the app as the "Nexus Mods App" - which is what was originally decided in the early days of the project. 

## We want
The design team have now asked us to refer to the app as the "Nexus Mods app" and put less emphasis on the "app" part. Eventually being compatible with the "Discord app" in that it's only really called an "app" to differentiate it from the web version. 

- [ ] Update documentation (in progress).
- [ ] Change the application name on the OS Chrome to "Nexus Mods".
- [ ] Change the application name when installed on Windows to "Nexus Mods" so that it appears this way in the list of installed programs. 
- [ ] Consult @captainsandypants for any additional changes. 

## Images
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/881d624e-1354-42d0-a5f8-527897b5a2c9)
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/70ddc073-1423-4fa6-bbd2-e943065e8fc7)

**Comment by Pickysaurus** [comment]
Docs are now updated.
