### ISSUE TITLE
Collections Spike

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1705]
Investigate the technical aspects of collections and how we will begin to implement them. 

Phase 1 will be downloading and installing collections.

- [x] Interpreting the nxm:// links containing a collection payload.
- [x] Requesting the collection bundle from the Graph API.
- [x] Inspecting the collection bundle to identify the manifest file.
- [x] Inspecting the collection bundle to identify any supplementary metadata.
- [x] Inspecting the collection bundle to identify any bundled mods.
- [x] ~~Show the pre-install instructions.~~ Removed as this is part of the UI side of things
- [x] ~~Check the user's game version against the one used to make the collection.~~ Also a UI constraint for most (all?) games?

**Comment by LukeNexusMods** [comment]
Here are the notes from Mikes ticket around the current functionality of downloading and installing collections. 

Downloading Collection Metadata

 Interpreting the nxm:// links containing a collection payload.
 Requesting the collection bundle from the Graph API.
 Inspecting the collection bundle to identify the manifest file.
 Inspecting the collection bundle to identify any supplementary metadata.
 Inspecting the collection bundle to identify any bundled mods.
 Show the pre-install instructions.
 Check the user's game version against the one used to make the collection.
