### ISSUE TITLE
Road to Loadout Items

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1763]
## Loadout Items

- [x] #1830
- [x] #1750
- [ ] Remove almost all references of "mod" from code :)
- [x] Rework installers, should integrate with library items
  - [x] #1785
  - [x] #1799
  - [x] #1801
  - [x] #1802
  - [x] FOMOD Installer (#1823)
  - [x] Advanced Installer (#1823)
- [x] Rework diagnostic emitters (only implementations, nothing else has to change)
  - [ ] #1784
  - [x] #1807
  - [x] #1809
- [x] Rework synchronizer
  - [x] #1805
  - [x] #1806
  - [x] #1826
- [ ] Rework VMs
  - [ ] Rework "Library" page (#1864)
  - [ ] Rework "My Mods" page (#1864)
  - [x] #1880
  - [x] Implement delete command in Loadout Grid (#1854)
  - [x] Replace `IModInfoViewModel` with `ILoadoutItemViewModel` for `LoadoutItem` instead of `Mod` (#1810)
    - [x] Replace `IModFilesViewModel` and `ModFileTreeViewModel` to work with `LoadoutFile`. (#1810)
    - [x] Implement `IFileTreeViewModel` for loadout items (#1810)
    - [x] Update text editor to accept `LoadoutFileId` instead of `FileId` (#1810)
  - [x] `IFileOriginsPage` use `ILibraryService` directly (#1828)
    - [x] `IFileOriginEntryViewModel` use `LibraryItem` instead of `DownloadAnalysis` (#1828)
  - [x] Update `LoadoutCardViewModel` to not use `Loadout.Mods.Count` for the mod count (#1830)
  - [ ] Complete rework of #1405, requires downloads and jobs
  - [x] Rework `LoadoutGrid` (#1810)
    - [x] Remove `Category` and `Version` column for now
    - [x] List `LoadoutItem` instead of `Mod`
    - [x] Rework columns, mostly just renaming from `Mod` to `LoadoutItem` for now
- [ ] Rework all tests
  - [ ] #1455
- [ ] Rework CLI verbs (or remove)
  - [ ] `stress-test`: uses `IHttpDownloader`, `IFileOriginRegistry`, and `IArchiveInstaller`
  - [ ] `download-and-install-mod`: uses `IHttpDownloader`, `IFileOriginRegistry`, and `IArchiveInstaller`
  - [ ] `analyze-archive`: uses `IFileOriginRegistry`
  - [ ] `install-mod`: uses `IFileOriginRegistry` and `IArchiveInstaller`
  - [x] `hash-folder` (#1843)

## Library

- [x] #1710
- [x] #1725
- [x] #1749
- [x] #1790 
- [ ] Replace "vanilla state loadout" and put vanilla state in library
- [x] Rethink how `IFileStore` is going to be used with the new library items. We also want new, or at least updated, trees.
- [ ] Remove `IArchiveInstaller` integrate its functionality into `ILibraryService`
- [x] Remove `IFileHashCache` (#1843)
- [ ] Replace `IFileOriginRegistry` with `ILibraryService`.
  - [x] `AddLocalFile` requires jobs
  - [x] `AddDownload` requires working downloads with jobs (#1835)

## Downloads

- [x] #1725
- [x] #1749
- [x] Replace `AdvancedHttpDownloader` and `SimpleHttpDownloader` with an implementation that users [Downloader](https://github.com/bezzad/Downloader) for simplicity. (#1832)
- [x] Integrate new job system with downloads (#1857)
  - [x] #1857
  - [x] Rework NXM IPC and protocol handlers (#1857)
- [ ] Replace `IFileOriginRegistry` with `ILibraryService`
- [ ] Adapt UI to jobs: #1405 (make use of new `ILibraryService` and jobs)

## Jobs

- [x] #1749
- [ ] Add progress to jobs, required for downloads
- [ ] Add child jobs to groups
- [x] Add persistent jobs, required for downloads (#1837)
  - [x] Add restarting of jobs on app restart
  - [x] Add persisting of jobs to the DB
- [x] Add global job list or per-service job list, required for downloads

##
  - [x] #1794

**Comment by Sewer56** [comment]
> Replace AdvancedHttpDownloader and SimpleHttpDownloader with an implementation that users [Downloader](https://github.com/bezzad/Downloader) for simplicity.

I have a question with respect to this.
I actually suggested using `Downloader` library all the way back in I think February-ish 2023, during standup.

I don't quite remember the exact reason why we didn't go with that.
Original Ticket: 
- https://github.com/Nexus-Mods/NexusMods.App/issues/20

I remember two of the talking points for running a custom solution were:

- Crash Tolerance
    - Downloader AFAIK does not periodically save state, so killing the App process would lose the download.
    - But for regular crashes it may be possible to save/restore with https://github.com/bezzad/Downloader?tab=readme-ov-file#how-to-stop-and-resume-downloads-other-time

- Alternative Source/Failover
    - The guys wanted to be able to do failover on individual chunks.
    - So say you're a premium user and you have access to 5+ servers. If one server dies, the App would pick up downloading that same chunk from another server, rather than restarting the whole download.

In any case, I don't remember the exact reasons, but maybe @halgari remembers.

**Comment by Sewer56** [comment]
Then at this point I'm not even sure why we've never used it.
Unless those are more recent features. I wasn't making the call on that.

**Comment by erri120** [comment]
This is done.
