### ISSUE TITLE
Recognise Game Updates automatically

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2231]
## Outline
As a user I want the app to recognise when a game update has happened and handle it gracefully. 

## Overview
There are several aspects of this ticket that are troublesome, but that all hinge on one issue: we don't have a source of truth for knowing what files in a game folder are part of what game install versions. We can ask GameFinder what games are installed, but the versions reported by the library are what Steam/GoG/Epic think is installed into that folder, if the files have diverged fromt he last time the store updated we have no way of knowing about this change. 

In addition since we don't know what files are acutally part of the install, we have no clean way to categorize the files into "game folders" and "mod folders". So that when an update arrives we don't have a way to know what changed files are part of changes made by the user or by the game store. 

## Tasks
Solving this issue will involve the following: 

- [x] Provide a CLI command for indexing a game folder, given a Version number, game name, and store id. From this folder we will index the following information: 
   - [x] xxHash3
   - [x] Minimalist Hash - defnition below
   - [x] MD5 Hash (for comparing against 3rd party CDNs)
   - [x] SHA1 Hash (for comparing against 3rd party CDNs)
   - [x] Size
   - [x] Path of the file
- [ ] Provide glob filters for known pure game / mod folders. We can assume any files in these folders are part of the game files. 
- [ ] Provide glob filters for known DLC / update paths
- [ ] Keep these files in a separate Github Repo in a folder structure that matches the game/store/version the data came from
- [ ] Write a github action that combines these files into a zip/nx archive and publishes them as a release file on the repo. Create a version number somehow linked to a github sha, so that the app can perform a query to github to know if a new release of this metadata is ready.
- [ ] Download these files from the repo as needed and keep a local up-to-date copy

Operations that can be performed on this data: 
1. To find the installed version of the code, compare what's in the game folder or in the loadout to the known data. Use the store data as a starting point, but do a fuzzy match were possible. For example, if the files match perfectly what is found in another store, we can use that store's version information

2. If the minimalist hash matches a file at a given path, there's no reason to hash the file, we can assume the file matches and use the xxHash3 file from the repo instead of hashing the file itself. Since most game files are not modified, this can save a ton of time in indexing files when managing games

3. When we see files update and change, we can compare the versions/paths/hashes to determine if the game updated, and update the game's version number accordingly

4. We can sort files into game groups/overrides/dlc as needed based on metadata. 

## Minimal Hashing Method
A major issue with our current hashing is that we try to hash the entire file. This is a requirement for the app to run correctly but is a problem on systems with slower disks. Our minimal hashing assumes that two files will not differ if they are found in the same location in the game folder, have the same size, and the start end and middle of the files do not differ. Therefore the algorithm for this hash is as follows: 

- If the file is under 128KB in size, hash the file via xxHash3. This is the result
- Create a buffer of 196616 bytes in size
- Read the first 64KB of the file
- Read the last 64KB of the file
- Read the middle 64KB of the file (may overlap with the last 64KB)
- Write 8bytes for the file length to the end of the file
- Hash the entire buffer via xxHash3, this is the result

Care should be used to only compare these hashes against files with the same hash location, but assuming the hash and location match, it is considered statistically improbable that the file has changed. Most game files are either compressed, minified, or otherwise compiled in such a way that it is improbable that the first, last and middle chunks all match *and* the file remain the same size, if something in the file has updated. 

So that I can update the game and continue to use the app without any issues

Currently when games update the app doesn't know and this can cause issues after the update. 

Notes from our meeting on this topic can be found here:
https://nexusmods.slack.com/docs/T0B8047QU/F07TZHWV248

**Comment by erri120** [comment]
Some GameFinder stuff:

- Steam
  - State flags: https://github.com/erri120/GameFinder/blob/master/src/GameFinder.StoreHandlers.Steam/Models/StateFlags.cs
  - Build ID: https://github.com/erri120/GameFinder/blob/cca71627f01133f45180e4de0d33fd5ad41349cb/src/GameFinder.StoreHandlers.Steam/Models/AppManifest.cs#L91-L101 to uniquely identify the installed build
  - many other cool stuff in the manifest
