### ISSUE TITLE
Load Order: TreeDataGrid RedMod backend

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#2275]
## Overview
Setup the TreeDataGrid infrastructure behind the scenes to allow showing Load Order

## Tasks:
- [x] #2285 
- [x] #2287 
- [x] #2289 
- [x] #2297 
- [ ] Use settings to persist
    - [ ] `SortDirectionCurrent`
        - [ ] #2303 
    - [x] `InfoAlertIsVisible`
- [x] Populate LoadOrderItemModel
    - [x] ModName
    - [x] IsActive
    - [x] UpCommand
    - [x] DownCommand
- [x] Implement Alert toggling functionality
- [x] Implement inverting the sorting (ascending/descending)
    - [x] Update IsWinnerTop accordingly
    - [x] Update up/down buttons accordingly
- [x] Move bindings to codebehind
- [ ] Move items to index (for Drag&Drop)

## Extras:
- [ ] Edit index functionality
    - [ ] Validate
    - [ ] Move to Index

**Comment by Al12rs** [comment]
The drag&drop functionality is tracked in 
- #2276 

This can otherwise be closed
