### ISSUE TITLE
Load Order - RedMod TreeDataGrid Drag&Drop support

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#2276]
## Outline
Add Drag&Drop support to TreeDataGrid load order

Please investigate Drag and Drop load order. How does it work with the current tree data grid? Is there anything we need to overcome before being able to implement. Provide estimates for the work to be completed

## Tasks:
- [x] #2885 
- [x] Add `TreeeDataGridAdapter` option to enable Drag&Drop #3019
    -  Add option flag
    - Enable drag and drop on the TreeDataGrid
    - Add virtual method for `OnRowDrop` that has the dragged models and target location data extracted from the original event args.
- [x] Update `LoadOrderTreeDataGridAdapter` to use Drag&Drop and call some stubbed `MoveItems` function on `ISortableItemsProvider`  #3026
- [x] Implement `MoveItems` with tests in `RedModSortableItemsProvider` that supports moving multiple items to a specific index #3031 
- [x] Fix gaps between UI items preventing making some drop operations fail #3035

## Needs investigation:
- Prevent dragging of items that can't be moved: not implemented since not needed for RedMods
- Prevent dropping of items in invalid locations: not implemented since not needed for RedMods
- UI and styling changes for drag and drop operations:
This seems quite tricky to change. We would need to completely replace the drop adorners with our own, with likely access problems to private treeDataGrid stuff. This is the relevant code: https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/blob/a684fd7d7f325f1134c7c43cc62af2f6ff727ff5/src/Avalonia.Controls.TreeDataGrid/TreeDataGrid.cs#L666

## DoD:
- User can drag and drop RedMod items in the Load Order view to change their sorting position.
- Sorting position is persisted across app restarts. 
- Starting the game has the redMods loaded correctly (harder to test, don't know which red mods work)

Load order is currently only available for Cyberpunk and only to sort RedMod type mods.
See comment below for a list of mods that would count.
Load order view can be accessed from the "New Tab" page, by selecting "Load Order WIP"

**Comment by insomnious** [comment]
RedMods to test:

- https://www.nexusmods.com/cyberpunk2077/mods/16256?tab=files
- https://www.nexusmods.com/cyberpunk2077/mods/14245?tab=files
- https://www.nexusmods.com/cyberpunk2077/mods/19817?tab=files

**Comment by Al12rs** [comment]
Finished with 
- #3031
