### ISSUE TITLE
Epic: Integrate GameFinder 3

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#285]
[GameFinder 3.0.0](https://github.com/erri120/GameFinder/blob/master/CHANGELOG.md#changelog) is a massive update with new features and breaking API changes:

- using `NexusMods.App.Paths` instead of `System.IO.Abstractions`. I'm currently using a git submodule, and the release is blocked until #104 published the required packages.
- added Xbox Game Pass support (#175)
- complete Wine support (#149, #150, #151, #201)
- using [`OneOf`](https://github.com/mcintyre321/OneOf) for results
- using [`Vogen`](https://github.com/SteveDunn/Vogen) for game Ids
- changed `AHandler<TGame, TId>` to require `TId : notnull`

This epic tracks the following tasks required for integration:

- [x] #104
- [x] create `XboxLocator` using `GameFinder.StoreHandlers.Xbox`
  - [x] update existing game support projects with Xbox support
- [x] add Wine support using `GameFinder.Wine`
