### ISSUE TITLE
Game Support - Skyrim Special Edition

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#33]
- Automatic Game Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Epic Games Launcher
  - [ ] Windows Game Store
- Game Version Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Epic Games Launcher
  - [ ] Windows Game Store

**Comment by Sewer56** [comment]
(Copied from #246)

## Work Items

As Skyrim Special Edition is a complex game, several items are required for comprehensive support.  These will need individual issues; and certain questions that will need to be answered.

[We should transfer these onto the Epic after merging this]

### 1. Basic game support

- Detect `.esp` plugins present in all mods to be deployed and export a new `plugins.txt` file with all `.esp`, `.esm`, `.esl`s that are enabled.
- Correctly deploy mods targeting the `Data` folder to the game folder.
- Correctly deploy mods targeting the base (exe) folder to the game folder.
- Provide adequate unit tests; using a stubbed game and either popular mods directly or stubbed versions of popular mods.

### 2. Handling of Missing Dependencies (Masters)

- If the master is available, what do we do UX wise?
  - Do we auto-enable the other mod?
  - Do we prompt the user?
- If the mater is not available, what do we do?
  - How do we convey this information to the user.
  
Ideally the user experience should be consistent within the app whenever possible; so how we have to handle similar situations in other games must be considered too.

### 3. Auto-installation of dependencies based on the user's mod loadout

- This is a complicated task from a UX perspective, as non-premium users cannot currently generate download links.
- How do we solve this?

### 4. Auto-install SKSE if missing and a mod depends on it

- Skyrim mods lack metadata; thus, we need to identify dependencies based on mod content or dependencies listed on the Nexus site and resolve this during download.
- The game should automatically launch `skse_loader64.exe` when the user hits 'Launch Game' if an SKSE-dependent mod is installed.

### 5. xEdit (SSEEdit) integration as a Tool

- We need to decide whether to:
  - Download xEdit out of the box.
  - Prompt the user to download xEdit. 
  - or have the user manually register their own copy.
  
As xEdit feels quite integral to the modding process.

### 6. Auto-install FNIS if an FNIS-dependent mod is installed

- FNIS needs to be automatically run before starting the game if the loadout is changed.
- FNIS should also be added as a Tool for manual running.

### 7. Integrated LOOT support

- A button for auto-sorting mods should be provided, at a minimum. More advanced functionality could be handled by LOOT's standalone program if necessary.
- This is currently blocked due to insufficient progress in UI/Game Management.
