### ISSUE TITLE
Epic: Breakup mono repo into multiple standalone repositories

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#370]
Tasks:
- [ ] Create a meta-repository
- [ ] Move libraries (and their tests) into their own repos:
  - [ ] `NexusMods.Paths` (+ the testing helper lib)
  - [ ] `NexusMods.Hashing.xxHash64`
  - [ ] `NexusMods.FileExtractor`
  - [ ] `NexusMods.DataModel.RateLimiting`
- [ ] Convert project references into package references

The meta-repository will be included by every other repository as a submodule, and the included files will be symlinked. It should include files like `.editorconfig`, `.gitignore`, `.gitattributes`, `LICENSE`, and pre-setup `.github/workflows`.

**Comment by Sewer56** [comment]
Potential candidate for closing in the future.
I checked off the other projects that got moved away from main in order to be more 'up to date'.

Another potential candidate for this is 'Workspaces'. I also considered 'Diagnostics', however that's so intrinsically tied to our DataModel that it perhaps is better left as part of the App itself.

**Comment by erri120** [comment]
This can probably be closed.
