### ISSUE TITLE
Epic: Loadouts

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#397]
# Epic

## Outline
We want to add a 'Loadouts' feature, which should allow users to to have multiple mod lists per game that they can quickly/easily switch between. Many of these issues require (https://github.com/Nexus-Mods/NexusMods.App/issues/1166) to be fixed, which is the question of "how do we know the base state of a game"

## Issues

- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/398
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1166
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/400
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/402
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/399
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/401
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/403
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/982
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/1177
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1193
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1195
- [x] #1197
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1204
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/1097
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/828
- [ ] https://github.com/Nexus-Mods/NexusMods.App/issues/1229
