### ISSUE TITLE
Loadout Synchronizer doesn't properly handle outside changes

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#422]
## The problem:
Currently, for the deployment of a loadout the code just compares the latest loadout revision with the current state of the file system and generates a list of steps to get the filesystem to match the state defined by the loadout revision.

This makes handling any changes to the filesystem that might have happened in the meantime hard. Currently there are some backup operations being performed for the reverted files, but there is no loadout revision node to actually reach that state.

The purpose here is to improve the handling of detected changes to the filesystem in both the cases of applications being run (Loot, xEdit) or users manually changing files (ini changes, mod creators creating/modifying files).
Specifically some cases were raised where keeping or merging changes would be necessary (outside ini edits, mod creators files, switching from one loadout to another).

## Example:
- User installs one mod and applies.
- User installs two other mods and doesn't apply yet.
- User changes the contents of an INI file from outside of NMA (perhaps for one of the mods).
- User applies the changes.

## Proposed solution:
It would be preferrable to have a loadout revision being created that references these outside changes, so that the user or the program can then reference them and decide whether to use them in any way.

In a discussion with @halgari, three concepts were defined when discussing outside changes:
- **Last Applied State (LAS)**:  reference to the last loadout revision that was successfully deployed to the filesystem.
- **File System State (FSS)**: current state of the relevant game folder/files
- **Planned State (PS)**: the loadout revision that the user will want to apply in the future, the head of the loadout tree.
 
The idea would be that of keeping track of the last loadout revision that was applied to the filesystem and perform diff towards that instead of the PlannedState. This way any detected changes can be applied as a separate revision on top of the Last Applied Revision and so can later be referenced if necessary.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/dd518958-94e6-42f2-9fb9-4ebd54d57234)

```mermaid
---
title: Trying to apply Planned State
---
flowchart TB
EQ{{"FileSystemState 
!= 
LastAppliedState"}}

R("Create new loadout revision at LastAppliedState with all FS changes")

MR("Merge new revision with PlannedTree
(multiple options)")

ML("Mark new revision as LastAppliedState")
UP("Update LastAppliedState and clear PlannedTree")

HC{{How to handle changes?}}

AP(Aplly head of PlannedTree to FS)

EQ-->|Different| R
R-->ML
ML-->HC
HC-->|Reject|AP
HC-->|Accept|MR
MR-->AP
EQ-->|Same| AP

AP-->UP
```

The idea is that after the FileSystem changes are ingested as a separate loadout revision, the program/user can decide whether to:
- Ignore all the changes
- Keep all the changes
- A mixture of the two (could either require user input or also be automatic through rules for specific paths)

Ignoring changes is the easiest as it would just allow us to go back to the previous loadout revision and ignore the newly created one.

If changes need to be kept though, the newly created revision with the outside changes needs to be merged with the Planned State tree in some way:
- Rebasing the Planned Tree on top of the new Outside Changes Revision
- Rebasing the Outside Changes Revision on top of the Planned Tree

The order could be important for configuration files that need to be merged with loadout revision changes

```mermaid
---
title: Before merge
---
flowchart LR
    R1(Rev01)-->R2-->R3
    
    subgraph LastAppliedState
    R2(Rev02)
    end
    subgraph FileSystemChanges
    R5(Rev05)
    end
    subgraph PlannedTree
    R3(Rev03)-->R4(Rev04)
    end
    R2-->R5
```

```mermaid
---
title: Rebase Planned Tree on top
---
flowchart LR
    R1(Rev01)-->R2-->R5-->R3
    
    R2(Rev02)
    subgraph FileSystemChanges
    R5(Rev05)
    end
    subgraph PlannedTree
    R3(Rev03)-->R4(Rev04)
    end
    
```

```mermaid
---
title: Merge FS changes on top
---
flowchart LR
    R1(Rev01)-->R2-->R3
    
    R2(Rev02)
    
    subgraph FileSystemChanges
    R5(Rev05)
    end
    subgraph PlannedTree
    R3(Rev03)-->R4(Rev04)-->R6(Rev06)
    end
    R2-->R5-->R6
```

## Concrete steps:

- [ ] Keep Track of Last Applied State
- [ ] Change `LoadoutSynchronizer.MakeApplySteps()` to not directly compare with the filesystem, and instead accept flattened file lists instead.
- [ ] Loadout revision needs to be added inside the Ingest step
- [ ] Change structure of apply logic to support automatic handling of outside changes (IgnoreAll/AcceptAll) or request user action.
- [ ] Allow loadout revisions to have more than one parent, to permit merging between Outside Changes and Planned Tree
- [ ] More stuff to be added here as we go along

## Still open issues:

While writing this I realized that there might be situations where it might not be desirable to always create the Outside Changes Revision on top of the Last Applied Revision. For example if the user intended those changes for a different loadout or revision (profile), or simply wanted to apply them on top of the Planned State.
Some discussion or consideration might be in order on whether the target revision on which to attach the outside changes should always be LAS or could be something else.

This approach still does an automatic loadout revision with outside changes, something that traditionally doesn't happen for version control systems and might be undesirable (unnecessary revision spamming).

An alternative would be to investigate what VCS do and look whether there are approaches that could adapted for our use case (stashes? staging concepts?).
A good case can be made to say that what NMA is trying to do is basically version control the entire mod process, with the distinction that all the loadout revisions that the user does in the modlist are basically like fetching changes from a remote, while the filesystem represents the working tree.

**Comment by Al12rs** [comment]
Instead of using loadout revisions for the outside changes (LastAppliedState, FileSystemState) it might be better to just use some form of dedicated hash folder snapshot data structure, and then keep track of these separately from loadouts.

Specifically this would simplify the handling of generated files, that can't be saved like other files in the loadout revisions as they haven't been generated yet when the revision is created, while the directory snapshot could hash the applied results of the generated files for comparison purposes.

Instead of revision these snapshots could be considered more like git stashes.

**Comment by Al12rs** [comment]
Also see #658 for additional Synchronizer issues.

**Comment by Al12rs** [comment]
## Requirements and questions for Synchronizer:
	- Allow games/users to exclude files/patterns from being managed.
	- Decide what to do for Mod files that end up in unmanaged area, not deploy them?
	- Users/games might also want to exclude mod files from being deployed, while still keeping the file in the mod, so this could be combined.
	- Normal mod files, outside changes policy:
		- Automatically accept outside changes.
		- Automatically reject outside changes.
		- Adaptive (after running a program, accept changes, reject them the rest of the time). Can be confusing for users.
		- Interactive decision (Ask user when mismatch is detected, what Vortex currently does).
		- Some sort of MO2 Overwrite kind of solution, with a dedicated place for detected changes and a way to rebase/merge stuff when the user wants to rather than immediately.
	- Allow game/users to define policy per
		- Game Location ID
		- Mod
		- Files
		- Pattern
		- Tool being executed 
		- And decide priority between these.
	- Are generated files part of the new design?
		- Different types of Generated files:
			- Solely and completely managed by NMA (something like code generated files, which ignore and overwrite any user tampering).
			- Cases requiring Merging, partially managed by NMA, but accepts user or outside changes (e.g. plugins.txt, we need to pick up Loot's changes or user changes and integrate them).
				- This is complicated, because it requires deciding when to overwrite hard disk and when to try to integrate the changes.
			- Files generated by a third party utility (Fnis, Nemesis, some other sort of patcher). These are not Generated by NMA, but should be integrated in the loadout.
	- If changes are ingested, where are the new changes put?
		- A new mod (Could cause mod spam)
		- A dedicated mod (like MO2 Overwrite, contents gets messy)
		- The highest priority mod containing those files.
		- A dedicated mod for the Tool that was just executed (e.g. FNIS output mod)
	- How to handle Nested game location IDs (GameRoot, Data):
		- Always use most top level (could be incorrect depending on installation differences (epic vs steam)).
		- Always use most nested (same issue, but also can have mods with some files in based on Data, some based on Root), makes finding mod files matching a particular path harder.
		- Use priority, like what we do for mods? It goes in the Location ID with the highest priority. Same issue as above regarding finding nested files.
	- Allow replacing Synchronizer with other deployment methods in the future (links, VFS, compacting into single file, etc)
	- Consider ad-hoc approaches for games that don't have file conflicts (separate mod folders), e.g. each mod folder is a separate location, support rename tracking of mod folders, link changes in mod folder directly to mod.
