### ISSUE TITLE
Add instrumentation (Traces and Metrics)

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#432]
Followup on #235.

## Tasks

- [x] Create [`NexusMods.App.Telemetry`](https://github.com/Nexus-Mods/NexusMods.App.Telemetry) repository containing everything related to telemetry. Every project that wants to expose telemetry has to use this project, and telemetry definitions have to be put into the new repository.
- [x] Create documentation for developers on telemetry is to be integrated: [docs](https://nexus-mods.github.io/NexusMods.App.Telemetry/)
- [x] publish package to nuget
- [x] configure package in the main app
- [ ] Optionally: Create documentation for users
- [x] Provide a UI for users wanting to opt-out (https://github.com/Nexus-Mods/NexusMods.App/issues/451)

## Note

As part of #370, all telemetry definitions should be contained in a separate repository `NexusMods.App.Telemetry`. Having everything related to telemetry in a single repository, allows us (developers and other project maintainers) to quickly figure out which metrics the app exposes, what they represent and what data type they are.

This also has the added benefit of being transparent to the users, which can get a better understanding of the data the app is gathering and transmitting.
