### ISSUE TITLE
Game Support - Mount & Blade 2: Bannerlord

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#45]
## Outline

The desired outcome of this issue is that Mount & Blade 2 Bannerlord:

- is automatically detected; AND
- game version is detected; AND
- can be managed by Nexus Mods App; AND
- the most common mods can be installed; AND
- the game starts with mods installed (and the mods work).

...for all applicable game stores (see below).

## Supporting Information

- Automatic Game Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Epic Games Launcher
  - [ ] Windows Game Store
- Game Version Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Epic Games Launcher
  - [ ] Windows Game Store
- Game Managed
  - [ ] Steam
  - [ ] GOG
  - [ ] Epic Games Launcher
  - [ ] Windows Game Store

**Comment by Aragas** [comment]
I'll gladly take the game under maintenance. I developed a C# library for Launcher management that's intended to be shared across Vortex, NexusMods.App and the vanilla Bannerlord launcher
