### ISSUE TITLE
Epic: Fix Flaky Tests

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#486]
Flaky tests are tests that have different test results even if the source code didn't change. These types of tests halt development and prevent PRs from getting merged. They might hide core issues or just small bugs that aren't tested directly.

Related Issues:

- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/372
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/443
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/436
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/433
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/439
- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/487
- [ ] #534
- [x] #536
- [ ] `NexusMods.UI.Tests.LoadoutGridViewModelTests.CanDeleteMods`: [non-concurrent collection was modified](https://github.com/Nexus-Mods/NexusMods.App/issues/486#issuecomment-1759228210).

**Comment by Al12rs** [comment]
Added #536

**Comment by halgari** [comment]
All of this has resulted in tests that past first time at least 90% of the time.

**Comment by Al12rs** [comment]
#534 is still failing, even locally.

**Comment by erri120** [comment]
This seems to be a regression introduced in #697 @halgari :

```
2023-10-11T13:51:57.9104325Z ##[error]System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
2023-10-11T13:51:57.9113119Z 
2023-10-11T13:51:57.9113652Z   Failed NexusMods.UI.Tests.LoadoutGridViewModelTests.CanDeleteMods [1 ms]
2023-10-11T13:51:57.9114173Z   Error Message:
2023-10-11T13:51:57.9115126Z    System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
2023-10-11T13:51:57.9115886Z   Stack Trace:
2023-10-11T13:51:57.9116280Z      at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
2023-10-11T13:51:57.9116825Z    at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
2023-10-11T13:51:57.9117658Z    at NexusMods.StandardGameLocators.TestHelpers.StubbedGames.StubbedGame.ResetGameFolders() in /home/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs:line 68
2023-10-11T13:51:57.9118813Z    at NexusMods.StandardGameLocators.TestHelpers.StubbedGames.StubbedGame.get_Installations() in /home/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs:line 79
2023-10-11T13:51:57.9119625Z    at NexusMods.UI.Tests.AVmTest`1..ctor(IServiceProvider provider) in /home/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.UI.Tests/AVmTest.cs:line 51
2023-10-11T13:51:57.9120422Z    at NexusMods.UI.Tests.LoadoutGridViewModelTests..ctor(IServiceProvider provider) in /home/runner/work/NexusMods.App/NexusMods.App/tests/NexusMods.UI.Tests/RightContent/LoadoutGridViewModelTests.cs:line 12
2023-10-11T13:51:57.9121168Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2023-10-11T13:51:57.9121758Z    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by halgari** [comment]
This new issues was fixed as part of the bug fixes for the loadout syncrhonizer integration
