### ISSUE TITLE
Create panel container

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#674]
# Chore

## Implementation TODOs

- [ ] Workspace
  - [x] has panels (#688)
  - [x] panels can be added (#688, #704)
    - [ ] offer a "default" option
      - [ ] prefer columns to rows when horizontal
      - [ ] prefer rows to columns when vertical
    - [x] images are auto-generated (#704)
    - [x] support for 2x2 (#704)
      - [x] 1 panel -> add column or row
      - [x] 2 columns/rows -> add new panel in one of the corners
      - [x] 2 columns -> add new panel as a top/bottom row (#814)
      - [x] 2 rows -> add new panel as a left/right column (#814)
  - [x] can be serialized and deserialized (#731)
- [ ] Panels
  - [x] can be closed (#704)
    - [x] prefer columns to rows when horizontal (#708)
    - [x] prefer rows to columns when vertical (#708)
  - [x] can be swapped (#704)
  - [x] ~~can be resized~~ (handled in #705)
  - [ ] can be popped out into its own window
  - [x] contains tabs (#708)
- [x] Tabs
  - [x] has an icon (#708)
  - [x] has a title (#708)
  - [x] has contents (#708)
  - [x] can be selected (#708)
  - [x] can be closed (#708)
  - [x] empty tabs contain a selection screen (#768)
- [ ] Styling
  - [ ] Workspace
    - [ ] Add panel icons
    - [ ] Add panel icon drop-down menu
  - [x] Panels
    - [x] tab header strip
      - [x] tabs (#708)
      - [x] plus button (#708)
      - [x] close button (#708)
      - [x] popout button (#708)
      - [x] close and popout button only visible when you have multiple panels (#768)
  - [x] Tabs
    - [x] tab header
      - [x] icon (#708)
      - [x] title (#708)
        - [x] long titles should be truncated with `...` (#708)
      - [x] close button (#708) 

## Requirements
This issue is to create a new panel container UI pattern, which can be extended across existing views within the app in follow-up issues.

Containers will need to contain UI grids, with up to four panels. Opening a new panel should be possible via the newly updated top navigation bar.

New panels should split the largest existing container in half, either vertically or horizontally (as chosen the by user).

Panels will need to contain tabs, opened or closed from within the panel. Eventually new tabs will display list menus of views that could be opened, but for this issue we're only concerned with opening and closing tabs.

Users should be able to "popout" existing panels, which effectively removes them from the other panels splitting in the container.

Layouts should be saveable and persist across sessions/machines.

See the epic for further details: https://github.com/Nexus-Mods/NexusMods.App/issues/418

### Figma links

[Create new tab - Figma user journey](https://www.figma.com/file/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1Panel-management?type=design&node-id=106%3A36451&mode=design&t=DBKRk6m8McSVRNJp-1)

[Create new panel and pop panel out in new window - Figma journey](https://www.figma.com/file/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1Panel-management?type=design&node-id=106%3A43434&mode=design&t=DBKRk6m8McSVRNJp-1)

[Figma prototype for panels and tabs](https://www.figma.com/proto/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1Panel-management?page-id=106%3A36450&type=design&node-id=106-36772&viewport=2551%2C598%2C0.42&t=NxZiGN2nqPr6XFDY-1&scaling=min-zoom&starting-point-node-id=106%3A36772&mode=design)
(Creating new tabs, adding panels and opening panels in a new window are possible in this prototype)

### Video demo

https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/120434f2-0bd3-46ba-ae3d-3edb8916578d

## Scenario 1
**Given** I am viewing a container with one panel

**When** I add a new right column panel

**Then** I see the new panel appears to the right on the existing one

## Scenario 2
**Given** I am viewing a container with two vertically split panels

**When** I add a new bottom right panel

**Then** I see the new panel appears horizontally split on the right

## Scenario 3
**Given** I am viewing a container with two vertically split panels

**When** I add a new bottom left panel

**Then** I see the new panel appears horizontally split on the left

## Scenario 4
**Given** I am viewing a container with one full length left panel and two vertically split right panels

**When** I add a new bottom left panel

**Then** I see the new panel appears horizontally split on the left

## Scenario 5
**Given** I am viewing a container with one full length right panel and two vertically split left panels

**When** I add a new bottom right panel

**Then** I see the new panel appears horizontally split on the right

## Scenario 6
**Given** I am viewing a container with one panel

**When** I add a new bottom row panel

**Then** I see the new panel appears below the existing one

## Scenario 7
**Given** I am viewing a container with two horizontally split panels

**When** I add a new top right panel

**Then** I see the new panel appears horizontally split on the top row

## Scenario 8
**Given** I am viewing a container with two horizontally split panels

**When** I add a new bottom right panel

**Then** I see the new panel appears horizontally split on the bottom row

## Scenario 9
**Given** I am viewing a container with one top horizontal panel and two bottom split panels

**When** I add a new top right panel

**Then** I see the new panel appears horizontally split on the top row

## Scenario 10
**Given** I am viewing a container with one bottom horizontal panel and two top split panels

**When** I add a new bottom right panel

**Then** I see the new panel appears horizontally split on the bottom row

## Scenario 11
**Given** I am viewing a container at least one panel

**When** I add a new tab to a new panel

**Then** I see a new tab appear within the panel

## Scenario 12
**Given** I am viewing a panel with more than one tab

**When** I close an existing tab

**Then** I see the tab removed from the panel

## Scenario 13
**Given** I am viewing a panel

**When** I move the panel to popout

**Then** I panel, along with all of it's tabs, popout from the existing container\
**And** any other panels in the container realign to fill the space
