### ISSUE TITLE
Create new icons for panels

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#676]
# Chore

## TODOs

- [x] auto-generate layout images (#704)
- [x] `icon/navigation/arrow_drop_down_24px` for the panel multi-select drop-down (#708)
- [x] `icon/content/add_24px` for adding new tabs and panels (#708)
- [x] `icon/navigation/close_24px` for closing tabs and panels (#708)
- [x] `icon/action/open_in_new_24px` for popping out panels into a separate window (#708)
- [x] `tab_24px` new tab icon (#708)

## Requirements

We need to review the new design (see below) and ensure we've created icons for anything missing, this will need to include any in the top, left and spine navigation, as well as any used by the new panels.
