### ISSUE TITLE
Event Sourcing based dataModel Rewrite (ADR 0011)

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#733]
Rewrite app backend to log user operations as series of events that can be undone, rather than series of immutable loadout snapshots.
See [ADR 0011](https://github.com/Nexus-Mods/NexusMods.App/blob/6df4e1664a66826f7d3b9764704b90cece3257a8/docs/decisions/backend/0011-undo-via-event-sourcing.md) for more information.

**Comment by Al12rs** [comment]
Additional changes from #719 PR feedback:

- [ ] Rename `FromArchive` to something like `BackedFile` and potentially add more specialized Traits.
- [ ] Consider adding a trait describing files that were Ingested, or some other way to distinguish files that were ingested from files originated from a downloaded mod (and thus can potentially be downloaded again vs only available locally).
- [ ] Rename `DownloadRegistry` to something like `BackupRegistry` or something along those lines, in particular avoid using "download" in the name as this registry also handles indexing of files that were never downloaded (game files, ingested changes). 
- [ ] Attempt to move to a more functional system than the current Alter one (which had side effects of saving to db and updating loadout markers).
- [ ] Limit and make clear which interfaces have the power to mutate things (save stuff in db, update current index, create checkpoint snapshots etc).
- [ ] Rename DataStoreId nomenclature for loadout revisions ids, use something clearer like LoadoutRevId or SnapshotId.

**Comment by Al12rs** [comment]
This was already implemented
