### ISSUE TITLE
Advanced Installer Rework 

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#750]
The current version of the Advanced Installer was developed before we defined our UI coding guidelines and it needs to be rewritten to follow them. 
Main reason is that the current way the code is structured makes the entire thing very hard to work with. The new UI coding guidelines approaches should solve the majority of the issues there.

Follows a list of issues and improvements that need to be addressed with this rework:

## Problems to address:

- [x] Move the `AdvancedInstaller.cs` file to the main AdvancedInstaller project instead of in the AdvancedInstaller UI project.
- [x] Installer breaks in CLI settings. Add implementation of the installer that is CLI compatible (return nothing -> fail). Use DI to get the UI version in UI setting.
- [x] Remove the use of generics in AdvancedInstaller.cs, either use DI instead or just remove the need from the testing side.
- [x] Use a Window instead of an Overlay. This is to allow moving and resizing the window, which was problematic on size constrained displays. 
- [x] Code doesn't follow the new UI guidelines.
- [x] Restructure the code to be centralized in the main BodyVM, all other VMs should simple data containers with as little logic as possible.
- [x] Consider reducing the number of separate views, by compacting them.
- [x] Consider using Dynamic Data flat tree structure approach instead of the current one.
- [x] Rename the three ITreeEntryVM to differentiate them. 
- [x] Cleanup namespaces
- [x] Rework the Tests (likely remove them and consider writing new ones for the new version).
- [x] Properly comment the code.

### Missing features from previous version:

- [x] Dupe folder Pill
- [x] Folder merged Pill
- [x] Remove the code that populates the tree from the FS. Instead just populate using LocationIds.
- [x] Add more information to Suggested locations.
- [x] Show nested LocationIds in the Suggested section (e.g. Data for bethesda games)
- [x] Auto focus on the the editing box after pressing Create Folder Button.
- [ ] Consider adding a "Select children" option to folders in ModContent tree.
- [ ] Consider making expand/collapsing work when clicking a bit outside the expander icon or on entire entry except for buttons. 

## Open questions:

- [ ] If a user installs files to multiple LocationIds (e.g. Appdata and Game), should the installer create two mods, one with Game files and one with Appdata, or just a single mod containing the mix of game files?
- [ ] If the user installs stuff in a nested location, should the installer use GamePaths relative to the most nested location, or relative to the top level LocationId ( Game Vs Data). 

## TODO:
- [x] Make Advanced installer usable from UI (SSE and SLE default method for now).
- [x] Populate mod contents
- [x] Mod content select, select children recursively.
- [x] Close and cancel installation on Footer Cancel and Top right Close buttons.
- [x] Populate Suggested section with game locations
- [x] Pass in the mod name to UnsupportedModOverlay
- [x] Pass in the mod name to AdvancedInstallerOverlay
- [x] Cancel select functionality
- [x] Make Mod Name always Caps
- [x] Mapping functionality
- [x] "Select" button functionality on SuggestedEntry and SelectTreeEntry.
- [x] Remove mapping from ModContent view
- [x] Cleanup preview root node if empty.
- [x] Switch to Empty preview view if Preview is empty.
- [x] Show name of Mapped location on ModContentEntry.
- [x] Remove mapping from Preview view
- [x] Auto Expand new entries in Preview view (matching ModContent expanded state)
- [x] Enable Install button only when there is something to install.
- [x] Install button functionality.
- [x] "Create folder" functionality
  - [x] Edit button functionality
    - [x] Switch states and update view
    - [x] Focus on input TextBox 
  - [x] Save button functionality
    - [x] Validate text input
    - [x] Enable Save button only if text can be trimmed to a valid name
    - [x] Create new node for folder
    - [x] Create new "Create Folder node" under the new node.
    - [x] Save on Pressing Enter.
    - [ ] Scroll down to the created Entry.
    - [x] Expand created entry.
  - [x] Cancel button functionality
    - [x] Switch states and update view
  - [x] Remove created button functionality
- [x] Dupe folder pill
- [x] Folder merged pill 
- [x] Prefer Optional over Nullable
- [x] Add Optional.ValueOr(Value) extension, to avoid valueSelector overhead.
- [x] Optimize code to use TreeNodeVM.Parent 
- [x] Convert into window
- [x] Temp Suggested Sub header needs Game Name
- [x] Fix bug when removing child Items form preview not cleaning up correctly.
- [x] Remove Window TitleBar while keeping window move functionality.
- [x] See if you can't remove the failed installed mod when Install with Advanced  Installer.
- [x] When creating folders, check for existing ones, case insensitive.
- [x] Fix small X close icon.
- [x] Fix Button Text alignment.
- [x] Show selected item for Keyboard navigation.
- [x] Ask color for selected item -> the default blue is fine.
- [x] Highlight chevron during pointerover of expander.
- [x] Increase hitbox for expander interaction.
- [x] Fix DesignPreview.
- [x] Make Folders bold, files normal.
- [x] Use single tree for multiple roots (Preview and Selectable trees).
- [x] Nested LocationIds get added before the CreateNewFolder button, so the order is messed up.
- [x] Comments and cleanup
- [x] Expand ModContent folder on BeginSelect
- [x] Review/Fix Tests.
- [ ] Update UI coding guidelines for TreeDataGrid and trees in general.
- [ ] Add info on creating new window dialogs?
