### ISSUE TITLE
Consider replacing Vogen

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#751]
Vogen is overly complex and constantly has issues with Rider. An alternative: https://github.com/erri120/TransparentValueObjects

Requirements for the alternative where `T` is the inner type (e.g., `Guid`), and `VO` is the Value Object type (e.g., `MyId`):

- [x] `VO` has the same size and alignment as `T`.
- [x] Generates `public readonly T Value` field.
- [x] Generates `public static VO From(T value)` method.
- [x] Generates implementations of `object.GetHashCode`, `object.ToString` and `object.Equals`.
- [x] Generates implementations of `IEquatable<T>` and `IEquatable<VO>`.
- [x] Generates `==` and `!=` operators for all combinations between `T` and `VO`.
- [x] Generates explicit cast operators to convert between `T` and `VO`.
- [x] For `Guid`: generates a `public static NewId => From(Guid.NewGuid())` method.
- [x] Has opt-ins to specify a custom default value.
- [x] Has opt-ins to specify a custom default equality comparer.
- [x] Has opt-ins to generate a JSON converter.
- [x] Can be used with `BindTo`.

**Comment by erri120** [comment]
Using `BindTo` on a property that is a Vogen value object fails:

```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Vogen.ValueObjectAttribute`1..ctor(Vogen.Conversions, System.Type, Vogen.Customizations, Vogen.DeserializationStrictness, Vogen.DebuggerAttributeGeneration)'.
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes()
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetAttributes()
   at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at ReactiveUI.ComponentModelTypeConverter.<>c.<.ctor>b__3_0(ValueTuple`2 types, Object _) in /_/src/ReactiveUI/Platforms/net/ComponentModelTypeConverter.cs:line 30
   at Splat.MemoizingMRUCache`2.Get(TParam key, Object context) in /_/src/Splat/MemoizingMRUCache.cs:line 137
   at Splat.MemoizingMRUCache`2.Get(TParam key) in /_/src/Splat/MemoizingMRUCache.cs:line 113
   at ReactiveUI.ComponentModelTypeConverter.GetAffinityForObjects(Type fromType, Type toType) in /_/src/ReactiveUI/Platforms/net/ComponentModelTypeConverter.cs:line 37
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass2_0.<.cctor>b__2(ValueTuple`2 acc, IBindingTypeConverter x) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 30
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at ReactiveUI.PropertyBinderImplementation.<>c.<.cctor>b__2_0(ValueTuple`2 types, Object _) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 27
   at Splat.MemoizingMRUCache`2.Get(TParam key, Object context) in /_/src/Splat/MemoizingMRUCache.cs:line 137
   at Splat.MemoizingMRUCache`2.Get(TParam key) in /_/src/Splat/MemoizingMRUCache.cs:line 113
   at ReactiveUI.PropertyBinderImplementation.GetConverterForTypes(Type lhs, Type rhs) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 260
   at ReactiveUI.PropertyBinderImplementation.BindTo[TValue,TTarget,TTValue](IObservable`1 observedChange, TTarget target, Expression`1 propertyExpression, Object conversionHint, IBindingTypeConverter vmToViewConverterOverride) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 245
   at ReactiveUI.PropertyBindingMixins.BindTo[TValue,TTarget,TTValue](IObservable`1 this, TTarget target, Expression`1 property, Object conversionHint, IBindingTypeConverter vmToViewConverterOverride) in /_/src/ReactiveUI/Bindings/Property/PropertyBindingMixins.cs:line 333
   at NexusMods.App.UI.ReactiveUiExtensions.BindToVM[TValue,TTarget](IObservable`1 this, TTarget target, Expression`1 property) in /home/florian/projects/NexusMods.App/src/NexusMods.App.UI/ReactiveUIExtensions.cs:line 56
```
