### ISSUE TITLE
Switch the datamodel to Event Sourcing

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#794]
# Epic

## Outline
The Event Sourcing code has gone through a lot of changes, and so this epic is used to track the issues associated with it, and to be upfront from the time spent on this subproject. 

## Issues
- [x] Core library development
  - [x] https://github.com/Nexus-Mods/NexusMods.EventSourcing/issues/12
  - [x] https://github.com/Nexus-Mods/NexusMods.EventSourcing/issues/11
  - [x] https://github.com/Nexus-Mods/NexusMods.EventSourcing/issues/13
  - [x] https://github.com/Nexus-Mods/NexusMods.EventSourcing/issues/15
  - [x] https://github.com/Nexus-Mods/NexusMods.EventSourcing/issues/14
