### ISSUE TITLE
Implement Settings UI

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#920]
Needs #396 

Details are in #396 as well.

### Design

https://www.figma.com/file/rR0I4C46je8VwwqCdrpc5U/%F0%9F%93%B1%E2%9A%99%EF%B8%8F-Settings-page?type=design&node-id=155%3A4907&mode=design&t=y96yEjSE4IjI3YSh-1

**Demo**

https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/f4960247-c580-4084-b8c3-2975b59979da

Does not include search in the sidebar for the first iteration. 

# Implementation Breakdown:
### Settings to bring into UI:
- Language setting: Dropdown of strings
- Telemetry enable (bool toggle)
- Diagnostic setting minimum severity (enum)

## Backend:
- [x] Make settings builder create a UI digestible interface of individual settings (Name, description, section, needs restart, default value etc.) #1239

## Frontend:
- [x] Create Settings Page and general UI layout // skip sections in the central part as well (#1246)
- [ ] Implement specific setting value UIs:
  - [x] Show name, description (markdown), needs restart and value setter (#1246) : 
    - [x] Bool toggle (#1248)
    - [x] String dropdown (#1248)
- [ ] Settings UI - Add Dialog on save press in there are changes that need user to restart

### Simple version:
- [ ] Add Dialog for when you press Save and we require a restart (we can't restart for now, ask user to do it)

### For full version:
- [ ] Design how to describe each option for multi choice settings (combobox)
- [ ] Highlight modified settings in the ui (settings that no longer have the default value)
- [ ] Add button to reset to default value in case of modified

### For later:
- [ ] Settings UI - Add Dialog for Cancel button (You have unsaved changes)
- [ ] Settings UI - Add Dialog for Cancel button in case of required restart (You have unsaved changes with restart)
- [ ] Add sections
- [ ] Filter search
- [ ] Implement automatic restart of the App
    - [ ] Restart with our multi window approach might be a pain to implement
    - [ ] Add confirm dialog before restarting

**Comment by Al12rs** [comment]
Copied from the issue body:

### Missing from design:
We need Design for displaying settings with a Warning, such as Experimental or Not Recommended.

This came up in the context of offering an option to not Backup the game files when managing the game for the first time, which exposes the users to potential issues if the game updates, since we don't have the backups of the old files if the user wants to rollback.

**Comment by erri120** [comment]
Done with #1248, other issues moved to epic #1182.
