### ISSUE TITLE
Implement LeftMenu navigation

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#932]
Workspace integration removed the old Left Menu navigation.
No replacement was put in place.

This needs to be implemented to allow adding new pages to any of the workspaces and allow users to navigate between them.

This is also required for the Apply components, that will live in the Loadout Left menus.

Each mainwindow workspace has a different LeftMenu, but a workspace can exist without the leftmenu (e.g. in a popped out panel), so the LeftMenuVM should not live inside the workspace itself.

A factory can be used to generate a LeftMenu given a WorkspaceContext perhaps. 
Ideally left menus VMs would not be created and destroyed each time they are switched, so some component needs to maintain a list of the active ones.

EDIT:
## TODO:
- [x] Implement LeftMenuFactory for Loaodout
    - [x] Implement OpenLoadout page 
    - [x] Add My Mods button (doesn't show up currently)
- [x] Implement leftMenuFactory for Home
    - [x] Implement open Home Page
- [x] Implement leftMenuFactory for Downloads
    - [x] Implement open InProgress Page
- [x] Implement WorkspaceAttachmentsFactoryController
- [x] Create LeftMenus for each Workspace
- [x] Switch LeftMenu depending on active workspace
- [x] Implement primary and secondary default open page behaviors
- [x] Switch the active tab to the first one when non replacing existing tab.
- [x] Add default navigation to Home when app opens
- [ ] Add Apply button to LoadoutLeft manu?
- [ ] Implement way to get the names for each workspace (probably a property on the Workspace itself, can be updated externally, like the TabName
- [ ] Add name at the top of the Mainwindow topbar
