### ISSUE TITLE
Opening a window after the last window closes is not supported (5 second bug)

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#965]
# Opening a window after the last window closes is not supported

## Summary
There's a bug that we haven't encountered yet in the app, but yet still exists. When the UI starts, we do some one-shot startup code, that starts Avalonia and sets some flags. Once the last window exits, that code also exits. If we open two windows at once, that's fine, as the Avalonia code will stay alive as long as at least one window stays alive. But if we open a window, close it, and before the app exits (due to an inactivity timer) we try to open a new window, nothing will happen since Avalonia's one-shot routines have stopped and there is no window dispatcher. 

## How to fix
I think we should probably find a way to keep the Avalonia lifecycle alive as long as the single process server thread is alive. However we only want to start Avalonia if we need to open a window. So 

- [ ] Keep Avalonia lazy-loading
- [ ] Don't exit the Avalonia lifecycle until the single process server thread exits
- [ ] Make sure this all still works in the single-thread debug, debugger attached mode

**Comment by halgari** [comment]
Relevant code is in : https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/NexusMods.App/StartupHandler.cs#L37-L54

**Comment by Al12rs** [comment]
This is still an issue even after #972
Sometimes it works, other times it opens a console and fails after 5 seconds, depending on the timing of when the new instance is opened.

**Comment by halgari** [comment]
Fixed in #1345, we no longer interact with the main process this way
