### ISSUE TITLE
Update Color System to match changes on Figma

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#978]
Color system was adopted by the Front End team, and some things were changed with their feedback.

### TODO:
- [ ] Use new shorter and simplified names
- [ ] Use "Surface" instead of "Background"
- [ ] Strokes have an extra value:
    - [ ] Add Stroke Subdued using current Moderate color
    - [ ] Change current Moderate color to new value
- [ ] Update Warning colors to match
