### ISSUE TITLE
[Epic] Apply/Ingest issues

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#980]
# Epic

## Outline
Fix issues related to Apply/Ingest implementation.

## Issues

- [ ] Disabling mods and Applying leaves empty folder structures in game directory
- [ ] Second loadout ingests previously deployed loadout as game files on creation
- [ ] Ingest outside changes into last applied loadout instead of current one
- [ ] Outside changes are discarded on ingest (new loadout isn't used)
- [ ] `DiskState` is stored with loadout revision id that is not guaranteed to match the state
- [ ] Store last applied loadout and revision ID separate from DiskState
- [ ] Use unique key to identify a `GameInstallation` in the DataStore
