### ISSUE TITLE
As a user I want to see the Diff of Outside Changes vs Last Applied `DiskState`

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#998]
# User story

As a user I want to see a filesystem diff of detected outside changes with respect to what was last applied on disk.

## Epic:
- [ ] UI Design Diff Outside Changes vs Last Applied
- [ ] Diff Outside Changes vs Last Applied initial Implementation
- [ ] Diff Outside Changes vs Last Applied Refinements

**Comment by Al12rs** [comment]
The current Preview Changes page is only meant to show what is new from the Loadout side, and doesn't handle External Changes in a useful way.
